Add mod validation on user and room changes
ppy/osu-server-spectator pull request #60
Opened 2021-06-21 08:01 UTC by peppy

- Closes #45.
- Fixes the server-side portion of ppy/osu#13567.

2021-06-21 08:26 UTC, peppy commented
We probably also want checks that all `UserMods` are in `AllowedMods`. I'll either do that in this PR or a follow-up depending on review status.

2021-06-21 16:07 UTC, bdach requested changes

2021-06-21 16:11 UTC, bdach commented
I've already touched on this in one of the comments above, but depending on how paranoid we want to be, the next step would be to verify the validity of `AllowedMods` and `RequiredMods` themselves server-side, too.

2021-06-22 01:59 UTC, peppy commented on osu.Server.Spectator.Tests/MultiplayerFlowTests.cs
> +                    new APIMod(new OsuModApproachDifferent())
definitely for a separate PR, as this one is focused only on `UserMods`.

2021-06-22 04:00 UTC, peppy commented
> I've already touched on this in one of the comments above, but depending on how paranoid we want to be, the next step would be to verify the validity of `AllowedMods` and `RequiredMods` themselves server-side, too.

I'll do that in a separate PR today, I think. This one should still be fine to be merged on its own as an improvement over what we have, regardless.

2021-06-22 13:05 UTC, smoogipoo approved these changes
lgtm

2021-06-22 13:06 UTC, merged